services:
  nicegui:
    ports:
      - 8080:8080
    volumes:
      - ./app:/usr/app # mounting local app directory
      - ./data:/usr/data
    build: 
      context: .
      args:
        - PUID=1000 # change this to your user id
        - PGID=1000 # change this to your group id
    environment:

      - NICEGUI_STORAGE_SECRET="change-this-to-yor-own-private-secret"
