import signal
import logging

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from nicegui import ui

from app.config import app_config
from app.api.provisioning import router as provisioning_router
from app.api.device import router as device_router
from app.api.file import router as file_router

import app.ui.frontend as frontend

_main_log = logging.getLogger("uvicorn")


def _on_sigusr1(signum, frame) -> None:
    """Flush all in-process caches. Useful after out-of-band filesystem changes.

    Usage: kill -USR1 <pid>
    """
    from app.core.device.backend import flush_device_list_cache
    from app.core.telemetry.backend import flush_telemetry_backend_cache
    flush_device_list_cache()
    flush_telemetry_backend_cache()
    _main_log.info("SIGUSR1: all in-process caches flushed")


signal.signal(signal.SIGUSR1, _on_sigusr1)

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# @app.get("/")
# async def root():
#     return RedirectResponse(url="/ui")

@app.get("/health")
async def health():
    return {"status": "ok"}


app.include_router(provisioning_router, prefix='/api', tags=['provisioning'])
app.include_router(device_router, prefix='/api', tags=['device'])
app.include_router(file_router, prefix='/api', tags=['file'])
# doc endpoint generated by FastAPI
ui.run_with(app, storage_secret=app_config.nicegui_storage_secret)


if __name__ == '__main__':
    import uvicorn
    uvicorn.run(app, host='0.0.0.0', port=8000)

