import asyncio
import signal
import logging
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from nicegui import ui

from app.config import app_config
from app.api.provisioning import router as provisioning_router
from app.api.device import router as device_router
from app.api.file import router as file_router

import app.frontend as frontend

_main_log = logging.getLogger("uvicorn")


def _on_sigusr1(signum, frame) -> None:
    """Flush all in-process caches. Useful after out-of-band filesystem changes.

    Usage: kill -USR1 <pid>
    """
    from app.core.device.backend import flush_device_list_cache
    from app.core.telemetry.backend import flush_telemetry_backend_cache
    flush_device_list_cache()
    flush_telemetry_backend_cache()
    _main_log.info("SIGUSR1: all in-process caches flushed")


signal.signal(signal.SIGUSR1, _on_sigusr1)


async def _mqtt_loop_wrapper() -> None:
    from app.mqtt.backend import mqtt_main_loop
    await mqtt_main_loop()


@asynccontextmanager
async def lifespan(app: FastAPI):
    # Register callbacks to wire up MQTT ↔ file-backend without circular imports
    from app.core.file.backend import register_publish_callback, file_watcher_loop
    from app.mqtt.backend import publish_file, register_file_publish_callback

    register_publish_callback(publish_file)
    # Upload notifications from MQTT → file backend: no-op (upload = device→server,
    # no re-publish needed; state is updated by the watcher loop).
    register_file_publish_callback(lambda *args, **kwargs: None)

    # Start background tasks
    mqtt_task = asyncio.create_task(_mqtt_loop_wrapper())
    watcher_task = asyncio.create_task(file_watcher_loop())

    yield

    mqtt_task.cancel()
    watcher_task.cancel()
    try:
        await mqtt_task
    except asyncio.CancelledError:
        pass
    try:
        await watcher_task
    except asyncio.CancelledError:
        pass


app = FastAPI(lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# @app.get("/")
# async def root():
#     return RedirectResponse(url="/ui")

@app.get("/health")
async def health():
    return {"status": "ok"}


app.include_router(provisioning_router, prefix='/api', tags=['provisioning'])
app.include_router(device_router, prefix='/api', tags=['device'])
app.include_router(file_router, prefix='/api', tags=['file'])
# doc endpoint generated by FastAPI
ui.run_with(app, storage_secret=app_config.nicegui_storage_secret)


if __name__ == '__main__':
    import uvicorn
    uvicorn.run(app, host='0.0.0.0', port=8000)
